### ISSUE TITLE
Maquetacion web - historial vehiculo

### ISSUE THREAD

**Issue by hdseba33** [autotronica/autotronica#2]
## Historial de vehiculo
Se maquetará la pagina del historial de los vehiculos

**Comment by carlosruminott** [comment]
@hdseba33 este componente debería llamarse diagnóstico

**Comment by hdseba33** [comment]
@carlosruminott  no me queda claro, pensé que diagnostico se iba a crear en un componente nuevo. para realizar el escaneo en el momento.

**Comment by carlosruminott** [comment]
es que esto fue mal nombrado, enrealidad es un resultado de diagnóstico, y la otra vista donde se ven los diferentes vehículos es el historial de escaneos ralizados

**Comment by hdseba33** [comment]
finalizado
