### ISSUE TITLE
# HTML

### ISSUE THREAD

**Issue by hdseba33** [autotronica/autotronica#7]
Agregar el menu en el componente navbar

**Comment by hdseba33** [comment]
### Acotación
@carlosruminott  el navbar tiene que estar en el componente `navbar` despues en el principal yo los comunico con la etiqueta de dicho componente. Lo mismo para el footer

**Comment by carlosruminott** [comment]
si, me imaginé. lo agregue ahí para que lo visualizaran, ya lo voy a poner en el compenente nvabar

**Comment by hdseba33** [comment]
👍

**Comment by hdseba33** [comment]
finalizado
