### ISSUE TITLE
diagrama flujo de la app

### ISSUE THREAD

**Issue by carlosruminott** [autotronica/autotronica#8]
![flujo-de-la-app](https://user-images.githubusercontent.com/2465194/29593522-36d9be94-8781-11e7-807b-9bd5c131d83c.png)

**Comment by hdseba33** [comment]
# Duda
El listado de vehiculos se en encuentra en el inicio?

**Comment by carlosruminott** [comment]
en el inicio deberían estar los botones no mas

**Comment by hdseba33** [comment]
ok

**Comment by carlosruminott** [comment]
ok!

**Comment by hdseba33** [comment]
finalizado
